### ISSUE TITLE
Release plans? :)

### ISSUE THREAD

**Issue by azazdeaz** [jerry73204/apriltag-rust#1]
Hi, this is some outstanding work! I'd love to be able to use it! Do you have any plans to release this crate in the future? I tried to fix that `todo!()` in the detect function but this stuff is way beyond me. Otherwise, if you could use any help from a beginner rustacean please let me know :)

**Comment by jerry73204** [comment]
@azazdeaz Thanks for your star! I'm busy in my errands so I cannot give an explicit release schedule. Nevertheless, now the code runs and I wrote an example [here](https://github.com/jerry73204/apriltag-rust/blob/master/examples/detector.rs). You can test it with the image in `test_data` directory.
The rests are writing tests and doc comments so that I can be confident to put it on crates.io. It may happen several weeks later.

**Comment by azazdeaz** [comment]
Wooow, thank you so much!!! It works like a charm! :heart::heart::heart: 
![](https://media.giphy.com/media/F6PFPjc3K0CPe/giphy.gif)

**Comment by jerry73204** [comment]
I made it available on [crates.io](https://crates.io/crates/apriltag). Check it out!.
